config/routes.rb
Rails.application.routes.draw do
  root :to => "home#index"

  get 'home/index' => 'home#index'
  get 'home/join' => 'home#join'

  resources :diary, only: [:create, :update], :as => :activities

  get 'diary/list' => 'diary#list'
  get 'diary/new/:date' => 'diary#new', :as => :diary_new
  get 'diary/edit/:date' => 'diary#edit', :as => :diary_edit

  get 'auth/:provider/callback', to: 'sessions#create' 
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy'

  get 'stat' => 'stat#show'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
	belongs_to :user
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :activity
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :alcohols
	has_many :comments

	def self.from_omniauth(auth)
	  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
	    user.provider = auth.provider 
	    user.uid      = auth.uid
	    user.name     = auth.info.name
	    user.save
	  end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery
  before_filter :login_check
   
  def login_check
    @current_user = nil
    if !session[:user_id].nil?
      begin
        @current_user = User.find(session[:user_id])
      rescue
        reset_session
        redirect_to '/home/join'
      end
    end
  end
end

app/controllers/diary_controller.rb
class DiaryController < ApplicationController

  def list    
    @activity = Activity.where(:user_id => @current_user.id)
    @activity_by_date = @activity.group_by(&:date) 
    @date = params[:date] ? Date.parse(params[:date]) : Time.zone.today.to_date
  end

  def new
    @activity = Activity.new  
  end

  def create
    p = params.require(:activity).permit(:user_id, :date, :alcohol, :exercise, :reading, :comment)
    @activity = Activity.create(p)

    respond_to do |format|
      format.js
    end
  end

  def edit
    @activity = Activity.find_by(date: params[:date])
  end

  def update
    @activity = Activity.find_by(date: params[:activity][:date])
    p = params.require(:activity).permit(:user_id, :date, :alcohol, :exercise, :reading, :comment)
    @activity.update(p)

    respond_to do |format|
      format.js
    end
  end

  def stat
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if !@current_user.nil?
      redirect_to "/diary/list"
    else
      redirect_to "/home/join"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    @current_user = nil
    redirect_to root_url
  end
end  

app/controllers/stat_controller.rb
class StatController < ApplicationController
  def show
    @activity = Activity.where(:user_id => @current_user.id)
    @date = params[:date] ? Date.parse(params[:date]) : Time.zone.today.to_date
    @week = (@date-7)..@date

    if @activity.count == 0
      flash[:notice] = "기록된 활동이 없습니다. 당신의 음주/운동/독서를 기록하고 통계를 확인하세요!"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def prettify(number)
    number.to_i == number ? number.to_i : number
  end
end

app/helpers/calendar_helper.rb
module CalendarHelper
	def calendar(date = Time.zone.today.to_date, &block)
		Calendar.new(self, date, block).table
	end

	class Calendar < Struct.new(:view, :date, :callback)
		HEADER = %w[월 화 수 목 금 토 일]
		START_DAY = :monday

		delegate :content_tag, to: :view

		def table
			content_tag :table, class: "table table-hover table-bordered" do
				header + week_rows	
			end
		end

		def header
			content_tag :tr do
				HEADER.map { |day| content_tag :th, day }.join.html_safe
			end
		end

		def week_rows
			weeks.map do |week|
				content_tag :tr do
					week.map { |day| day_cell(day) }.join.html_safe
				end
			end.join.html_safe
		end

		def day_cell(day)
			content_tag :td, view.capture(day, &callback), class: day_classes(day)
		end

		def day_classes(day)
			classes = []
			classes << "today" if day == Time.zone.today.to_date
			classes << "notmonth" if day.month != date.month
			classes << "beforetoday" if day <= Time.zone.today.to_date
			classes.empty? ? nil : classes.join(" ")
		end

		def weeks
			first = date.beginning_of_month.beginning_of_week(START_DAY)
			last = date.end_of_month.end_of_week(START_DAY)
			(first..last).to_a.in_groups_of(7)
		end
	end
end

app/helpers/diary_helper.rb
module DiaryHelper
	def table_cell type, number
		case type
		when "alcohol"
			case number 
			when 0.0 || nil
				a = "안먹음" 
			when 0.2  
				a = "맥주 쪼끔" 
			when 0.5  
				a = "반병"
			when 1.0 
				a = "한병" 
			when 1.5  
				a = "한병 반"
			when 2.0  
				a = "두병 이상(꽐라)" 
			end

			unless a == "안먹음"
				content_tag :span, class: "label label-danger" do
					"음주 : #{a}"
				end
			end
		when "exercise"
			case number 
			when 0.0 || nil
				a = "안함" 
			when 0.25  
				a = "15분" 
			when 0.5  
				a = "30분"
			when 0.75 
				a = "45분" 
			when 1.0  
				a = "1시간 이상" 
			end

			unless a == "안함"
				content_tag :span, class: "label label-success" do
					"운동 : #{a}"
				end
			end

		when "reading"
			case number 
			when 0.0 || nil
				a = "안읽음" 
			when 1.0  
				a = "1시간 이하" 
			when 2.0  
				a = "2시간"
			when 3.0 
				a = "3시간" 
			when 4.0  
				a = "4시간 이상" 
			end

			unless a == "안읽음"
				content_tag :span, class: "label label-info" do
					"독서 : #{a}"
				end
			end
		when "comment"
			unless number == nil? || number == ""
				content_tag :span, class: "label label-default" do
					"일기 : 씀"
				end		
			end
		end
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stat_helper.rb
module StatHelper
end

app/views/diary/_dialog.html.erb
<div class="modal fade"
id="dialog" tabindex="-1" role="dialog" 
aria-labelledby="myModalLabel"
aria-hidden="true" 
data-backdrop="static" 
data-keyboard="true">
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" 
      data-dismiss="modal" 
      aria-label="Close">
      <span aria-hidden="true">&times;</span></button>
      <h3 class="modal-title"><%= @date.to_date.strftime("%m월 %d일") %></h3>
    </div>
    <div class="modal-body">
    </div>
    
  </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/diary/_form.html.erb
<%= form_for(@activity, remote:true, :html => { :role => "form" }) do |f| %>

<div class="form-group">
  <div class="btn-group" data-toggle="buttons">
    <h3> 음주 </h3>
    <label class="btn btn-default active">
      <%= f.radio_button :alcohol, "0.0", :checked => (@activity.alcohol.nil? || @activity.alcohol == 0.0), :style=>'display:none;' %> 안먹음
    </label>
    <label class="btn btn-default">
      <%= f.radio_button :alcohol, "0.2", :checked => (@activity.alcohol == 0.2), :style=>'display:none;' %> 맥주 쪼끔
    </label>
    <label class="btn btn-default">
      <%= f.radio_button :alcohol, "0.5", :checked => (@activity.alcohol == 0.5), :style=>'display:none;' %> 반병
    </label>
    <label class="btn btn-default">
      <%= f.radio_button :alcohol, "1.0", :checked => (@activity.alcohol == 1.0), :style=>'display:none;' %> 한병
    </label>
    <label class="btn btn-default">
      <%= f.radio_button :alcohol, "1.5", :checked => (@activity.alcohol == 1.5), :style=>'display:none;' %> 한병 반
    </label>
    <label class="btn btn-default">
      <%= f.radio_button :alcohol, "2.0", :checked => (@activity.alcohol == 2.0), :style=>'display:none;' %> 두병 이상(꽐라)
    </label>
  </div>
</div>

<div class="form-group">
  <div class="btn-group" data-toggle="buttons">
    <h3> 운동 </h3>
    <label class="btn btn-default active">
      <%= f.radio_button :exercise, "0.0", :checked => (@activity.exercise.nil? || @activity.exercise == 0.0), :style=>'display:none;' %> 안함
    </label>
    <label class="btn btn-default">
      <%= f.radio_button :exercise, "0.25", :checked => (@activity.exercise == 0.25), :style=>'display:none;' %> 15분
    </label>
    <label class="btn btn-default">
      <%= f.radio_button :exercise, "0.5", :checked => (@activity.exercise == 0.5), :style=>'display:none;' %> 30분
    </label>
    <label class="btn btn-default">
      <%= f.radio_button :exercise, "0.75", :checked => (@activity.exercise == 0.75), :style=>'display:none;' %> 45분
    </label>
    <label class="btn btn-default">
      <%= f.radio_button :exercise, "1.0", :checked => (@activity.exercise == 1.0), :style=>'display:none;' %> 1시간 이상
    </label>
  </div>
</div>

<div class="form-group">
  <div class="btn-group" data-toggle="buttons">
    <h3> 독서 </h3>
    <label class="btn btn-default active">
      <%= f.radio_button :reading, "0.0", :checked => (@activity.reading.nil? || @activity.reading == 0.0), :style=>'display:none;' %> 안읽음
    </label>
    <label class="btn btn-default">
      <%= f.radio_button :reading, "1.0", :checked => (@activity.reading == 1.0), :style=>'display:none;' %> 1시간 이하 
    </label>
    <label class="btn btn-default">
      <%= f.radio_button :reading, "2.0", :checked => (@activity.reading == 2.0), :style=>'display:none;' %> 2시간
    </label>
    <label class="btn btn-default">
      <%= f.radio_button :reading, "3.0", :checked => (@activity.reading == 3.0), :style=>'display:none;' %> 3시간
    </label>
    <label class="btn btn-default">
      <%= f.radio_button :reading, "4.0", :checked => (@activity.reading == 4.0), :style=>'display:none;' %> 4시간 이상
    </label>
  </div>
</div>

<div class="form-group">
  <h3> 한줄 일기 </h3>
  <%= f.text_area :comment, :placeholder => '한줄 일기를 써 보세요. 정신건강이 좋아집니다.', id: "comment", class: "form-control", rows:8 %>
  <div id="preview" class="data-tooltip" data-toggle="tooltip" title="수정하기" style="display:none">
    <p id="preview_p" class="lead" style="display:none"><%= @activity.comment %></p>
  </div>
</div>
<%= f.hidden_field :date, value: params[:date] %>
<%= f.hidden_field :user_id, value: @current_user.id %>

<div class="form-group">
  <%= f.submit @activity.new_record? ? "추가하기" : "수정하기", :class => "btn btn-primary" %>
</div>
<% end %>

app/views/diary/_insert.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/diary/_intro.html.erb
<div class="modal fade" id="intro" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <h2> REA:Diary </h2>
        <h4> 술 안먹고 운동하고 책 읽고 열심히 잘 살아봅시다. </h4>
        <div class="row"> 
          <div id="calender_image">
            <img src="<%= image_path('calender.png') %>">
          </div>
          <div id="edu_text">
            <ul>
              <li>달력에 그날의 음주/운동/독서량을 표시하세요.</li>
              <li>한줄 일기도 쓸 수 있습니다.</li>
              <li>'통계'에서 내 지난 활동들을 확인하세요.</li>
              <li>자기관리를 못하는 스스로를 자책하고 이만큼 더 성장하세요.</li>
            </ul>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">닫기</button>
      </div>
    </div>
  </div>
</div>

app/views/diary/create.js.erb
$('#dialog').modal('toggle');
$('#diary').ready(function(){
	location.reload(true);
	});

app/views/diary/edit.js.erb
$('#dialog h3').html("<i class='glyphicon glyphicon-plus'></i> <%= params[:date].to_date.strftime("%m월 %d일") %>의 활동 수정하기");
$('.modal-body').html('<%= j render 'form' %>');
$('#dialog').modal("show");

var n = $('#preview_p').text().length;

if(n>0){
$('#preview').show();
$('#preview_p').show();
$('#comment').hide();
}

$('label:has(input:radio:checked)').addClass('active');
$('label:has(input:radio:not(:checked))').removeClass('active');
$('#preview').click(function(){
	$('#preview').hide();
	$('#comment').show();
});

$(function () {
  $('[data-toggle="tooltip"]').tooltip()
})

app/views/diary/list.html.erb
<%= render :partial => 'layouts/header' %>
<% if @activity.count == 0 %>
  <%= render 'intro' %>
  <%= javascript_tag "intro_modal()" %>
<% end %>

<div id="diary">
  <div class="container">
    <h3 id="month">
      <%= link_to "<", date: @date.prev_month %>
      <%= @date.strftime("%Y년 %m월") %>
      <%= link_to ">", date: @date.next_month %>
    </h3> 
  </div>
  <div class="container">
    <%= calendar @date do |date| %>
        <% if @activity_by_date[date] %>
          <% @activity_by_date[date].each do |a| %>
                <div class="data-tooltip" data-toggle="tooltip" title="수정하기">
                  <%= link_to diary_edit_path(date), :remote => true, :format => 'js' do %>
                  <span><%= date.day %></span>
                  <div class="label-wrapper"><%= table_cell("alcohol", a.alcohol) %></div>
                  <div class="label-wrapper"><%= table_cell("exercise", a.exercise) %></div>
                  <div class="label-wrapper"><%= table_cell("reading", a.reading) %></div>
                  <div class="label-wrapper"><%= table_cell("comment", a.comment) %></div>
                  <% end %>
                </div>
          <% end %>
        <% elsif date <= Time.zone.today.to_date %>
        <div class="data-tooltip" data-toggle="tooltip" title="추가하기">
          <%= link_to diary_new_path(date), :remote => true, :format => 'js' do %>
          <% end %>
        <% end %>
        <span><%= date.day %></span>
        </div>  
    <% end %>
  </div>
  <%= render 'dialog' %>

app/views/diary/new.js.erb
$('#dialog h3').html("<i class='glyphicon glyphicon-plus'></i> <%= params[:date].to_date.strftime("%m월 %d일") %>의 활동 기록하기");
$('.modal-body').html('<%= j render 'form' %>');
$('#dialog').modal("show");
$('label:has(input:radio:checked)').addClass('active');
$('label:has(input:radio:not(:checked))').removeClass('active');

app/views/diary/update.js.erb
$('#dialog').modal('toggle');
$('#diary').ready(function(){
	location.reload(true);
	});

app/views/home/join.html.erb
<div id="join">
  <div class="container">
    <div id="background">
      <div id="slogan">
        <%= image_tag("slogan.png") %>
      </div>
      <div id="sign_in_wrap">
        <div id="sign_in">
          <a href="/auth/facebook" id="sign_in" role="button" class="btn btn-info btn-block">페이스북 계정으로 시작</a>>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div id="nav">
	<nav class="navbar navbar-inverse navbar-static-top" role="navigation">
	  <div class="container">
	    <ul class="nav navbar-nav navbar-left">
	      <li class="<%= 'active' if params[:controller] == 'diary'%>"> <a href="/diary/list">기록하기</a></li>
	      <li class="<%= 'active' if params[:controller] == 'stat'%>"> <a href="/stat">통계</a></li>
	    </ul>
	    <ul class="nav navbar-nav navbar-right">
	      <li><%= link_to "로그아웃", signout_path, id: "sign_out" %></li>
	    </ul>

	  </div>
	</nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>REA:Diary</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>
</body>
</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert alert-info alert-dismissable fade in">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= message %>
  </div>
<% end %>

app/views/stat/show.html.erb
<%=	render :partial => 'layouts/header' %>

<div id="stat">
	<div id="week_ago">
		<div class="container">
			<% if @activity.count == 0 %>
				<%= render partial: "shared/flash_messages", flash: flash %>
			<% end %>

			<h3> <%= @current_user.name %> 님의 삶 </h3>
			<h3 id="change_week"><%= link_to "<", date: @date.prev_week %>
			<%= (@date-7).strftime("%m월 %d일") %> ~ <%= @date.strftime("%m월 %d일") %>
			<%= link_to ">", date: @date.next_week %></h3>
			<div class="row center-block">
				<div id="box_alcohol" class="col-md-4 center-block">
					<h4>음주</h4>
					<h1><%= prettify(@activity.where(:date => @week).sum(:alcohol)) %>병</h1>
				</div>
				<div id="box_exercise" class="col-md-4 center-block">
					<h4>운동</h4>
					<h1><%= prettify(@activity.where(:date => @week).sum(:exercise)*60) %>분</h1>
				</div>
				<div id="box_reading" class="col-md-4 center-block">
					<h4>독서</h4>
					<h1><%= prettify(@activity.where(:date => @week).sum(:reading)) %>시간</h1>
				</div>
			</div>
		</div>
	</div>

	<div id="graph">
		<div class="container">
			<div class="row center-block">
				<span class="title"><h3>음주</h3></span>
					<%= column_chart @activity.order(date: :desc).limit(30).group(:date).sum(:alcohol).sort.map {|k,v| {k.strftime("%m/%d") => v }.flatten}, colors: ["#d9534f"], library: {vAxis: {format: '#.#병', maxValue:2}, bar: {groupWidth:'30%'}} %>
			</div>
			<div class="row center-block">
				<span class="title"><h3>운동</h3></span>
					<%= column_chart @activity.order(date: :desc).limit(30).group(:date).sum(:exercise).sort.map {|k,v| {k.strftime("%m/%d") => v*60 }.flatten}, colors: ["#5cb85c"], library: {vAxis: {format: '#분', maxValue:60}, bar: {groupWidth:'30%'}} %>
			</div>
			<div class="row center-block">
				<span class="title"><h3>독서</h3></span>
					<%= column_chart @activity.order(date: :desc).limit(30).group(:date).sum(:reading).sort.map {|k,v| {k.strftime("%m/%d") => v }.flatten}, colors: ["#5bc0de"], library: {vAxis: {format: '#.#시간', maxValue:3}, bar: {groupWidth:'30%'}} %>
			</div>
		</div>
	</div>
</div>